### ISSUE TITLE
Minimal name length too high

### ISSUE THREAD

**Issue by nD00rn** [Chifilly/SimulTwitch#15]
**Describe the bug**
Streams with a lower length of 4 characters are not working.

**To Reproduce**
Steps to reproduce the behaviour:
1. Have a stream(ers) name with 3 characters.
https://simultwitch.com/sco (https://twitch.tv/sco)
https://simultwitch.com/orb (https://twitch.tv/orb)

I tried entering the names in the url, get redirected back to the main page.
Tried entering it in the input field at the top of the page, get redirected back to the main page / nothing happens.
Tried entering the Twitch URL in the input field in the top of the page and get redirected back to the main page / nothing happens.

**Expected behaviour**
Load sco's stream

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version v69.0.3497.100

**Additional context**
Seems there is a minimal length of 4 characters for streams to show.

**Comment by Chifilly** [comment]
Thanks for the report :)

I wasn't aware that Twitch names could be 3 characters long. To be safe, I changed the minimum length to 2.

This change is now live. Thanks again.
