### ISSUE TITLE
Support embedded darkmode chat

### ISSUE THREAD

**Issue by luisantonioa** [Chifilly/SimulTwitch#16]
**Describe the bug**
When dark mode is on in twitch the css for the chat is off and showing black text on a dark background.

If darkmode in simultwitch is enabled the embed url should be: 
https://www.twitch.tv/embed/CHANNEL/chat?darkpopout

The darkpopout bit makes the chat compatible with dark mode.. 

**To Reproduce**
* Enable dark mode in twitch website
* Use chat in simulcast website

**Expected behaviour**
Dark mode works correctly.

**Screenshots**
With normal dark mod eenabled on twitch:
![image](https://user-images.githubusercontent.com/891590/48391170-4a521900-e6ba-11e8-8215-a4d93fbc4756.png)

When i mod the iframe url to contain ?darkpopout
![image](https://user-images.githubusercontent.com/891590/48391233-91400e80-e6ba-11e8-843a-fd5ff8469ab6.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome
 - Version: 71.0.3578.30 (Official Build) beta (64-bit)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Chifilly** [comment]
I have implemented a solution for this

There are 2 new settings which have been added:

1. **Sync chat with theme**
This will synchronise the _darkpopout_ option in the Twitch chat embed URL with the current SimulTwitch dark theme setting. If this is enabled, the Twitch chat will use the dark version if the SimulTwitch dark theme is enabled, and will use the normal version if SimulTwitch dark theme is disabled
2. **Use Twitch dark chat**
This will enable or disable the chat dark theme manually. This setting will only be changeable if _Sync chat with theme_ setting is _disabled_

Both these settings are available in the sidebar under the _Theme_ section

Notes:  

- When the chat changes from dark to light or vice-versa, all chat boxes will refresh as the URL is getting changed
- If you have browser plugins that alter the chat (e.g. BetterTTV or FrankerFaceZ) your results may vary
